# Generated by Django 4.2.8 on 2023-12-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_custom',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
